version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
    command: >
      sh -c "
        echo 'Waiting for DBs...';
        while ! nc -z postgres 5432; do sleep 2; done;
        until mongosh --host mongo --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --eval 'rs.status().ok' &> /dev/null; do
          echo 'Waiting for MongoDB replica set...';
          sleep 5;
        done;
        npx prisma generate;
        npx prisma migrate deploy;
        node dist/server.js
      "
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo-keyfile-generator:
    image: alpine/openssl # Image with openssl, chmod, chown
    command: >
      sh -c "
        if [ ! -f /keyfiles/mongo-keyfile ]; then
          echo 'Generating MongoDB keyfile...';
          openssl rand -base64 756 > /keyfiles/mongo-keyfile;
          chmod 400 /keyfiles/mongo-keyfile;
          chown 999:999 /keyfiles/mongo-keyfile; # UID:GID for mongodb user in official mongo image
          echo 'MongoDB keyfile generated, permissions and ownership set.';
        else
          echo 'MongoDB keyfile already exists. Ensuring permissions and ownership.';
          chmod 400 /keyfiles/mongo-keyfile;
          chown 999:999 /keyfiles/mongo-keyfile;
        fi
      "
    volumes:
      - mongo_keyfile_volume:/keyfiles

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile
    volumes:
      - mongo_data:/data/db
      - mongo_keyfile_volume:/etc/mongo-keyfile:ro # Mount the keyfile read-only
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --eval 'db.runCommand(\"ping\").ok'"]
      interval: 10s
      timeout: 20s
      retries: 15
      start_period: 60s
    depends_on:
      mongo-keyfile-generator:
        condition: service_completed_successfully # Ensures keyfile is ready

  mongo-init:
    image: mongo:6
    depends_on:
      mongo:
        condition: service_healthy
      # mongo-keyfile-generator: # Implicitly handled as 'mongo' depends on it
      #   condition: service_completed_successfully
    entrypoint: >
      bash -c "
        echo 'Initiating single-node replica set...';
        mongosh --host mongo -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongo:27017\" }]
          })'
        echo 'Replica set initialized.'
      "
    env_file:
      - .env
    networks:
      - app-network

volumes:
  pg_data:
  mongo_data:
  mongo_keyfile_volume: {} # Define the shared volume for the keyfile

networks:
  app-network:
    driver: bridge