# .github/workflows/hello-world.yml

name: VPS Deploy Workflow

on:
    workflow_dispatch:
      

jobs:
  deploytovps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to VPS
        run: |
          ssh root@69.62.85.32 
          ls
