# .github/workflows/hello-world.yml

name: VPS Deploy Workflow

on:
    workflow_dispatch:
      

jobs:
  deploytovps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      
      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 69.62.85.32 >> ~/.ssh/known_hosts

      - name: Copy code to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 69.62.85.32
          username: root
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/root/app"
      
      - name: Rebuild and start containers on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 69.62.85.32
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/app
            docker compose down || true
            docker compose up --build -d